<a href="https://colab.research.google.com/github/AngelikaBaloy/DS1002/blob/main/Copy_of_07_More_Pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# More pandas exercises

Create a Colab notebook. Complete the tasks as specified in the directions. Run each cell to return the desired output. Save your notebook back to your GitHub repository and submit the GitHub URL for your notebook for review.

1.  Load the following dataset into Colab and perform the requested operations in code.

 Source: https://ds1002-resources.s3.amazonaws.com/data/ride_sharing.csv

In [ ]:
# Load pandas and the data
import pandas as pd
ride_data = pd.read_csv('https://ds1002-resources.s3.amazonaws.com/data/ride_sharing.csv')
ride_data.head()

,duration,station_A_id,station_A_name,station_B_id,station_B_name,bike_id,user_type,user_birth_year,user_gender,tire_size
0,12 minutes,81,Berry St at 4th St,323,Broadway at Kearny,5480,2,1959,Male,26
1,24 minutes,3,Powell St BART Station (Market St at 4th St),118,Eureka Valley Recreation Center,5193,2,1965,Male,27
2,8 minutes,67,San Francisco Caltrain Station 2 (Townsend St...,23,The Embarcadero at Steuart St,3652,3,1993,Male,29
3,4 minutes,16,Steuart St at Market St,28,The Embarcadero at Bryant St,1883,1,1979,Male,26
4,11 minutes,22,Howard St at Beale St,350,8th St at Brannan St,4626,2,1994,Male,27

In [ ]:
# show how many rows and columns are in this dataset
ride_data.info()
## there are 25760 rows and 10 columns

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 25760 entries, 0 to 25759
Data columns (total 10 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   duration         25760 non-null  object
 1   station_A_id     25760 non-null  int64
 2   station_A_name   25760 non-null  object
 3   station_B_id     25760 non-null  int64
 4   station_B_name   25760 non-null  object
 5   bike_id          25760 non-null  int64
 6   user_type        25760 non-null  int64
 7   user_birth_year  25760 non-null  int64
 8   user_gender      25760 non-null  object
 9   tire_size        25760 non-null  int64
dtypes: int64(6), object(4)
memory usage: 2.0+ MB

In [ ]:
# The first column, "duration" is seen as a string.
# Using two snippets of code, clean this column up so that
# is now an integer (int64)
ride_data["duration"] = ride_data["duration"].str.strip('minutes') #takes out 'minutes'
ride_data["duration"] = ride_data["duration"].astype('int') #converts the str to int

In [ ]:
ride_data.head(2) #just wanted to make sure it worked

,duration,station_A_id,station_A_name,station_B_id,station_B_name,bike_id,user_type,user_birth_year,user_gender,tire_size
0,12,81,Berry St at 4th St,323,Broadway at Kearny,5480,2,1959,Male,26
1,24,3,Powell St BART Station (Market St at 4th St),118,Eureka Valley Recreation Center,5193,2,1965,Male,27

In [ ]:
# Now display the datatypes in the updated dataframe
ride_data.dtypes #3 objects and the rest are int

duration            int64
station_A_id        int64
station_A_name     object
station_B_id        int64
station_B_name     object
bike_id             int64
user_type           int64
user_birth_year     int64
user_gender        object
tire_size           int64
dtype: object

In [ ]:
# Show the min and max values of ride durations (the shortest and longest rides)
# Hint: If 'df' is the name of your dataframe, simply specify the column name
# and then append the .min() or .max() methods.
ride_data['duration'].describe()
## min: 1 // max: 1372

count    25760.000000
mean        11.389053
std         23.500516
min          1.000000
25%          6.000000
50%          9.000000
75%         13.000000
max       1372.000000
Name: duration, dtype: float64

In [ ]:
# Create a new dataframe object and populate it with rides that are 60 minutes or less.
# Hint: Use the .query() method for the dataframe that we used in class.
new_df = ride_data[ride_data.duration <= 60] # using .query() didn't come to mind first but i provided that method below
new_df
# or new_df = ride_data.query('duration < 60')

,duration,station_A_id,station_A_name,station_B_id,station_B_name,bike_id,user_type,user_birth_year,user_gender,tire_size
0,12,81,Berry St at 4th St,323,Broadway at Kearny,5480,2,1959,Male,26
1,24,3,Powell St BART Station (Market St at 4th St),118,Eureka Valley Recreation Center,5193,2,1965,Male,27
2,8,67,San Francisco Caltrain Station 2 (Townsend St...,23,The Embarcadero at Steuart St,3652,3,1993,Male,29
3,4,16,Steuart St at Market St,28,The Embarcadero at Bryant St,1883,1,1979,Male,26
4,11,22,Howard St at Beale St,350,8th St at Brannan St,4626,2,1994,Male,27
...,...,...,...,...,...,...,...,...,...,...
25755,11,15,San Francisco Ferry Building (Harry Bridges Pl...,34,Father Alfred E Boeddeker Park,5063,1,2000,Male,26
25756,10,15,San Francisco Ferry Building (Harry Bridges Pl...,34,Father Alfred E Boeddeker Park,5411,2,1998,Male,26
25757,14,15,San Francisco Ferry Building (Harry Bridges Pl...,42,San Francisco City Hall (Polk St at Grove St),5157,2,1995,Male,26
25758,14,15,San Francisco Ferry Building (Harry Bridges Pl...,42,San Francisco City Hall (Polk St at Grove St),4438,2,1995,Male,27
25759,29,16,Steuart St at Market St,115,Jackson Playground,1705,3,1990,Male,27

In [ ]:
# Now show both the min and max values of the duration column for your new dataset.
new_df['duration'].describe()
# min: 1 // max: 60

count    25544.000000
mean        10.142930
std          6.876427
min          1.000000
25%          6.000000
50%          9.000000
75%         12.000000
max         60.000000
Name: duration, dtype: float64

In [ ]:
# Using the new dataframe, update it so that is ONLY has records where
# the tire_size is 26.
new_df = new_df.query('tire_size == 26')
new_df.head() #new_df is now shorter in length
# len(new_df) = 12761

,duration,station_A_id,station_A_name,station_B_id,station_B_name,bike_id,user_type,user_birth_year,user_gender,tire_size
0,12,81,Berry St at 4th St,323,Broadway at Kearny,5480,2,1959,Male,26
3,4,16,Steuart St at Market St,28,The Embarcadero at Bryant St,1883,1,1979,Male,26
6,16,67,San Francisco Caltrain Station 2 (Townsend St...,107,17th St at Dolores St,1035,2,1981,Male,26
9,5,30,San Francisco Caltrain (Townsend St at 4th St),62,Victoria Manalo Draves Park,333,1,1994,Male,26
12,7,3,Powell St BART Station (Market St at 4th St),27,Beale St at Harrison St,1863,3,1998,Male,26

In [ ]:
# Finally, produce a count of all records with FEMALE riders
# using the 26-inch wheeled rental bikes for their rentals of
# one hour or less.
new_df.query('user_gender == "Female"') #gives the df
len(new_df.query('user_gender == "Female"')) #gives the length of the df, len = 2962

2962

2. Find the file `more-messy-data.csv` on Canvas and upload it into Google Colab.

Create a new Pandas DataFrame from that data and perform the following steps.

In [ ]:
#upload
messy_data = pd.read_csv('/very-messy-data.csv')
messy_data.head()

   id  sepal_length  sepal_width  petal_length  petal_width    species
0   1           3.5          2.9           1.4          0.5  virginica
1   2           3.6          3.2           3.0          0.5     setosa
2   3           3.8          NaN           2.2          1.5     setosa
3   4           5.8          2.7           2.6          1.2  virginica
4   5           4.9          3.6           3.0          1.2  virginica

In [ ]:
messy_data['species'].describe()

count        934
unique         2
top       setosa
freq         484
Name: species, dtype: object

In [ ]:
# Write a snippet of code that will display the number of duplicate rows exist in the DF.
print(messy_data.duplicated().sum()) #there are 316 duplicate rows

316

In [ ]:
# Next, remove all duplicate rows using Python.
messy_data = messy_data.drop_duplicates()

In [ ]:
# For the FOUR columns involving sepal and petal length and width, update all NaN
# values with the column mean.
messy_data_fill = messy_data.fillna(messy_data.mean()) #there are still missing values in the species column because there is not a species mean (it's categorical)
messy_data_fill

<ipython-input-69-c937846a7168>:3: FutureWarning: The default value of numeric_only in DataFrame.mean is deprecated. In a future version, it will default to False. In addition, specifying 'numeric_only=None' is deprecated. Select only valid columns or specify the value of numeric_only to silence this warning.
  messy_data_fill = messy_data.fillna(messy_data.mean()) #there are still missing values in the species column because there is not a species mean (it's categorical)

       id  sepal_length  sepal_width  petal_length  petal_width    species
0       1           3.5     2.900000      1.400000     0.500000  virginica
1       2           3.6     3.200000      3.000000     0.500000     setosa
2       3           3.8     2.987694      2.200000     1.500000     setosa
3       4           5.8     2.700000      2.600000     1.200000  virginica
4       5           4.9     3.600000      3.000000     1.200000  virginica
..    ...           ...          ...           ...          ...        ...
995   996           4.5     3.600000      2.000442     2.700000     setosa
996   997           4.0     2.100000      2.000442     2.100000     setosa
997   998           5.9     2.500000      2.100000     2.500000  virginica
998   999           5.0     2.600000      1.900000     1.561863        NaN
999  1000           3.4     3.900000      1.900000     1.500000     setosa

[1000 rows x 6 columns]

In [ ]:
# Find any values in the dataframe that are still missing, and delete them.
clean_data = messy_data.dropna()
clean_data
## len(clean_data) # len = 608 now

       id  sepal_length  sepal_width  petal_length  petal_width    species
0       1           3.5          2.9           1.4          0.5  virginica
1       2           3.6          3.2           3.0          0.5     setosa
3       4           5.8          2.7           2.6          1.2  virginica
4       5           4.9          3.6           3.0          1.2  virginica
5       6           5.0          2.7           1.4          2.3     setosa
..    ...           ...          ...           ...          ...        ...
991   992           3.7          2.5           2.6          2.8  virginica
993   994           4.5          3.7           1.2          0.3  virginica
994   995           4.0          2.9           1.0          0.2  virginica
997   998           5.9          2.5           2.1          2.5  virginica
999  1000           3.4          3.9           1.9          1.5     setosa

[608 rows x 6 columns]

In [ ]:
# How many different species are there?
clean_data['species'].describe() #it says there are only 2 different species

count        608
unique         2
top       setosa
freq         310
Name: species, dtype: object

In [ ]:
# Clean up the 'species' variable so that there are exactly three different values.
## i'm not sure about this because there are only two species

3. Bonus:  Regular expressions

Ordinary (non-vanity) Virginia license plates have the form `ABC1234`, meaning they have three upper case letters followed by four digits.  Write a regular expression that matches any string of this form (and doesn't match anything else).  Test your expression with code to make sure it works.

To figure out out how to do this, start with the sample code below.  The `re` package has various functions related to regular expressions, including for example `match()`, which takes two arguments, first the regular expression and second the test string, and tests to see whether the *beginning* of the `test` string matches the pattern `exp`.

Note that `re.match(exp,test)` does not return a boolean variable, as you might expect (in other words, a match doesn't return `True` and a non-match `False`).  The type of object you get is called `re.Match`, which is a data type special to the `re` package.  (The reason for this is that the object contains more information than just whether there is a match or not.) However, you can turn it into a boolean using `bool()` if you want.

Include the following in the notebook you submit:

 1. A regular expression in a text chunk
 2. One or more code chunks in which you test several strings to verify that your regex is correct.
 3. Make sure you display the results of testing various strings.

 See this [documentation page](https://docs.python.org/3/howto/regex.html#regex-howto) for further help.

In [85]:
# Sample code for testing whether a string matches a regex

# First import this package for working with regular expressions
import re

# Here is an example.
# Play around with different expressions and test strings to see what happens.
exp = 'ab+'
test = 'accccbbb'

if re.match(exp,test):
  print("match!")
else:
  print("no match")

# uncomment this line if you want
print(type(re.match(exp,test)))

# uncomment this line if you want
print(bool(re.match(exp,test)))

no match
<class 'NoneType'>
False

In [86]:
# Sample code for testing whether a string matches a regex

# First import this package for working with regular expressions
import re

# Here is an example.
# Play around with different expressions and test strings to see what happens.
exp = 'ab+'
test = 'abcccbbb'

if re.match(exp,test):
  print("match!")
else:
  print("no match")

# uncomment this line if you want
print(type(re.match(exp,test)))

# uncomment this line if you want
print(bool(re.match(exp,test)))

match!
<class 're.Match'>
True

In [93]:
exp = '[A-Z][A-Z][A-Z][0-9][0-9][0-9][0-9]' #i'm not sure if i understood the prompt correctly but this is what i came up with
test = 'ABC1234'

if re.match(exp,test):
  print("match")
else:
  print("no match")

match

In [94]:
exp = '[A-Z][A-Z][A-Z][0-9][0-9][0-9][0-9]'
test = 'abc1234' #tried putting lowercase test

if re.match(exp,test):
  print("match")
else:
  print("no match")

no match

In [95]:
exp = '[A-Z][A-Z][A-Z][0-9][0-9][0-9][0-9]'
test = 'ZCQ2219' #tried different letters and numbers but correct format

if re.match(exp,test):
  print("match")
else:
  print("no match")

match

In [96]:
exp = '[A-Z][A-Z][A-Z][0-9][0-9][0-9][0-9]'
test = '9901234' #tried all numbers

if re.match(exp,test):
  print("match")
else:
  print("no match")

no match

In [97]:
exp = '[A-Z][A-Z][A-Z][0-9][0-9][0-9][0-9]'
test = 'AB1234' #tried missing letter

if re.match(exp,test):
  print("match")
else:
  print("no match")

no match